Setting up sandbox installation

diff --git a/sandbox/configure-sandbox b/sandbox/configure-sandbox
--- a/sandbox/configure-sandbox
+++ b/sandbox/configure-sandbox
@@ -31,19 +31,12 @@ cd $CSG_TOP
 # $DT_TOP/bin/create-file-from-template.py -t $XYZ_SANDBOX/git_project/etc/httpd.conf.template -o $XYZ_SANDBOX/conf/httpd.conf
 
 # If the sandbox uses node, wipe the node_modules and re-install during re-configuration
-if [ -f $CSG_TOP/package.json -a -n "$CSG_NODE_VER" ]; then
-	[ -d $CSG_TOP/node_modules ] && /bin/rm -rf $CSG_TOP/node_modules
-	if [ "$CSG_YARN" == true ]; then
-		[ ! -f $CSG_TOP/yarn.lock ] && echo "WARNING: yarn.lock not found - creating one"
-		echo "yarn install (from `pwd`)"
-		yarn install --frozen-lockfile
-		[ $? -ne 0 ] && echo "yarn install failed" && [ $abort_on_fail -eq 1 ] && exit 1
-	else
-		echo "npm install --no-save (from `pwd`)"
-		npm install --no-save
-		[ $? -ne 0 ] && echo "npm install failed" && [ $abort_on_fail -eq 1 ] && exit 1
-	fi
-fi
+cd $CSG_TOP/docs
+[ -d node_modules ] && /bin/rm -rf node_modules
+echo "npm install --no-save (from `pwd`)"
+npm install --no-save
+[ $? -ne 0 ] && echo "npm install failed" && [ $abort_on_fail -eq 1 ] && exit 1
+cd $CSG_TOP
 
 # Optional NPM package integrity check
 # To set this integrtity check up, you must manually create (and maintain) a file containing
